name: Render-KiCAD

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.3
        with:
        # Required - kibot config file
          config: /opt/kibot/config/docs.schema.kibot.yaml
        # optional - prefix to output defined in config
          dir: docs
        # optional - schematic file
          schema: 'TasmoTree/*.sch'
        # optional - PCB design file
          board: 'TasmoTree/*.kicad_pcb'
        # optional - verbose output info
          verbose: 1
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}